<table class="descuentos">
    <tr>
        <th>C</th>
        <th>D</th>
        <th>A & E</th>
        <th>A</th>
        <th>B</th>
		<th>G</th>
    </tr>
    <tr>
        <td><b>A</b></td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
		<td>0</td>
    </tr>
    <tr>
        <td><b>B</b></td>
        <td>5</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
		<td>0</td>
    </tr>
    <tr>
        <td><b>C</b></td>
        <td>10</td>
        <td>8</td>
        <td>5</td>
        <td>0</td>
		<td>8,2</td>
    </tr>
    <tr>
        <td><b>D</b></td>
        <td>15</td>
        <td>8</td>
        <td>8</td>
        <td>0</td>
		<td>8,2</td>
    </tr>
    <tr>
        <td><b>E</b></td>
        <td>20</td>
        <td>10</td>
        <td>10</td>
        <td>5</td>
		<td>13,61</td>
    </tr>
    <tr>
        <td><b>F</b></td>
        <td>25</td>
        <td>18</td>
        <td>17</td>
        <td>15</td>
		<td>19</td>
    </tr>
    <tr>
        <td><b>G</b></td>
        <td>30</td>
        <td>20</td>
        <td>20</td>
        <td>17</td>
		<td>21</td>
    </tr>
    <tr>
        <td><b>H</b></td>
        <td>32</td>
        <td>24</td>
        <td>20</td>
        <td>17</td>
		<td>24,4</td>
    </tr>
    <tr>
        <td><b>J</b></td>
        <td>35</td>
        <td>26</td>
        <td>24</td>
        <td>17</td>
		<td>26,54</td>
    </tr>
    <tr>
        <td><b>K</b></td>
        <td>40</td>
        <td>32</td>
        <td>32</td>
        <td>25</td>
		<td>29,8</td>
    </tr>
    <tr>
        <td><b>L</b></td>
        <td>45</td>
        <td>37</td>
        <td>35</td>
        <td>25</td>
		<td>35,19</td>
    </tr>
    <tr>
        <td><b>M</b></td>
        <td>50</td>
        <td>42</td>
        <td>37</td>
        <td>30</td>
		<td>40,59</td>
    </tr>
    <tr>
        <td><b>N</b></td>
        <td>55</td>
        <td>47</td>
        <td>40</td>
        <td>35</td>
		<td>46</td>
    </tr>
    <tr>
        <td><b>R1</b></td>
        <td>25</td>
        <td>21</td>
        <td>17</td>
        <td>15</td>
		<td>51,37</td>
    </tr>
</table>